[versions]
springBoot = "3.2.5"

[libraries]
springBootStarterSecurity = {module = "org.springframework.boot:spring-boot-starter-security", version.ref = "springBoot"}
springSecurityTest = {module = "org.springframework.boot:spring-security-test", version.ref = "springBoot"}

[plugins]
springDependencyManagement = { id = "io.spring.dependency-management", version =  "1.1.4"}
springBoot = { id = "org.springframework.boot", version =  "3.2.5"}
